routes/auth.py
from flask import Blueprint, request, flash, redirect, render_template, session, url_for, g
from flask_bcrypt import Bcrypt
from sqlalchemy.exc import IntegrityError
from models import db, User
from forms import LoginForm, RegistrationForm
from routes.profile import flash_errors
from routes.helpers import add_user_to_g, do_login, do_logout, CURR_USER_KEY

auth_bp = Blueprint("auth", __name__)

bcrypt = Bcrypt()

@auth_bp.before_request
def before_request():
    add_user_to_g()

############################################################################################################
# Login a user

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    # Check if user is already logged in
    if 'user_id' in session:
        return redirect(url_for('index'))
    
    form = LoginForm(request.form)
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        
        # Check if username and password are not empty
        if not username or not password:
            return render_template('login.html', form=form, error_message='Username and password are required'), 401
        
        user = User.authenticate(username, password)

        if user:
            do_login(user)
            return redirect(url_for('index'))
        else:
            return render_template('login.html', form=form, error_message='Invalid username or password'), 401
    else:
        return render_template('login.html', form=form)
    

############################################################################################################
# Register a user

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    """Handle user registration."""
    form = RegistrationForm(request.form)
 
    if form.validate_on_submit():
            try:
                if form.password.data != form.password_confirm.data:
                    raise ValueError("Passwords do not match")
                
                hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

                user = User(
                    username=form.username.data,
                    email=form.email.data,
                    password=hashed_password,  # Store hashed password in the database
                )
                db.session.add(user)
                db.session.commit()

                # Automatically log in the user after registration
                do_login(user)

                print("User registered successfully!")
                return redirect(url_for('index'))  # Redirect to index page after registration
            
            except ValueError as error:
                # Handle ValueError (likely due to passwords not matching)
                error_message = str(error)
                print("ValueError:", error_message)
                return render_template('register.html', form=form, error_message=error_message)
            
            except IntegrityError as error:
                # Handle IntegrityError (e.g., duplicate username or email)
                error_message = "Username or email already exists."
                return render_template('register.html', form=form, error_message=error_message), 400

    else:
        # Form validation failed, render form with error messages
        flash_errors(form)
        print("Validation failed:", form.errors)
        return render_template('register.html', form=form)
        
def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(f"Error in {getattr(form, field).label.text}: {error}", "error")


############################################################################################################
# Logout a user                                               

@auth_bp.route('/users/logout', methods=['POST'])
def user_logout():
    """Handle logout of user."""
    # Clear the session (logout the user)
    do_logout()

    # Redirect the user to the homepage
    return redirect(url_for('index'))

routes/author_profile.py
from flask import Blueprint, render_template, redirect, url_for, flash
from models import User, Post, Like, Comment
from routes.helpers import add_user_to_g, do_login, do_logout, CURR_USER_KEY
import os

author_profile_bp = Blueprint('author_profile', __name__)

############################################################################################################
# Author profile

#Upon clicking the author's name for a post, the user should be redirected to the author's profile page.
@author_profile_bp.route('/author/<username>')
def author_profile(username):
    """Display author profile."""
    author = User.query.filter_by(username=username).first()
    if not author:
        # Handle case where author does not exist
        flash('Author not found', 'error')
        return redirect(url_for('index'))  # Redirect to homepage or appropriate page

    # Fetch author's posts
    author_posts = Post.find_user_posts(username)

    # Pre-process image URLs
    for post in author_posts:
        post.img_url = url_for('post.serve_uploaded_image', filename=os.path.basename(post.img_path))

    return render_template('author_profile.html', author=author, author_posts=author_posts)

# Route to display posts of a specific author
@author_profile_bp.route('/author_posts/<username>')
def author_posts(username):
    """Display posts of a specific author."""
    author = User.query.filter_by(username=username).first()
    if not author:
        flash('Author not found', 'error')
        return redirect(url_for('index'))

    # Fetch author's posts
    author_posts = Post.query.filter_by(fk_userid=author.id).all()

    # Pre-process image URLs for author's posts
    for post in author_posts:
        post.img_url = url_for('post.serve_uploaded_image', filename=os.path.basename(post.img_path))

    return render_template('author_posts.html', author=author, author_posts=author_posts)

# Route to display posts liked by a specific author
@author_profile_bp.route('/author_likes/<username>')
def author_likes(username):
    """Display posts liked by a specific author."""
    # Fetch the user based on the username parameter
    author = User.query.filter_by(username=username).first()
    if not author:
        flash('Author not found', 'error')
        return redirect(url_for('index'))

    # Fetch the liked posts of the author
    liked_posts = (
        Post.query
        .join(Like, Post.id == Like.post_id)
        .join(User, Like.user_id == User.id)
        .filter(User.username == username)
        .all()
    )

    # Pre-process image URLs for liked posts
    for post in liked_posts:
        post.img_url = url_for('post.serve_uploaded_image', filename=os.path.basename(post.img_path))

    return render_template('author_likes.html', author=author, liked_posts=liked_posts)

# Route to display comments made by a specific author
@author_profile_bp.route('/author_comments/<username>')
def author_comments(username):
    """Display comments made by a specific author."""
    author = User.query.filter_by(username=username).first()
    if not author:
        # Handle case where author does not exist
        flash('Author not found', 'error')
        return redirect(url_for('index'))  # Redirect to homepage or appropriate page
    
    # Fetch author's comments
    author_comments = (
        Comment.query
        .join(User, Comment.fk_userid == User.id)  # Join Comment with User
        .filter(User.username == username)  # Filter comments by username
        .order_by(Comment.created.desc())
        .all()
    )

    # Pre-process image URLs for each comment's associated post
    for comment in author_comments:
        comment.post.img_url = url_for('post.serve_uploaded_image', filename=os.path.basename(comment.post.img_path))

    return render_template('author_comments.html', author=author, author_comments=author_comments)

# Route to display the about page of a specific author
@author_profile_bp.route('/author_about/<username>')
def author_about(username):
    """Display the about page of a specific author."""
    author = User.query.filter_by(username=username).first()
    if not author:
        flash('Author not found', 'error')
        return redirect(url_for('index'))

    return render_template('author_about.html', author=author)

routes/profile.py
from flask import Flask, Blueprint, request, flash, send_from_directory, redirect, current_app, render_template, session, url_for, g
from flask_bcrypt import Bcrypt
from werkzeug.utils import secure_filename
import os

from models import db, User, Comment, Post, Like, View
from forms import EditProfileForm
from routes.helpers import add_user_to_g, do_login, do_logout, CURR_USER_KEY

profile_bp = Blueprint('profile', __name__)

app = Flask(__name__)

bcrypt = Bcrypt(app)

@profile_bp.before_request
def before_request():
    add_user_to_g()

############################################################################################################
# User profile

#Upon clicking the profile button, the user should be redirected to the profile page.
@profile_bp.route('/profile')
def profile():
    """Display user profile."""
    user = g.user
    if not user:
        return redirect(url_for('login'))

    # Fetch user's upload count
    upload_count = user.uploads

    # Calculate total views for the user's posts
    total_views = user.calculate_total_views()

    # Pass the username to the template
    username = user.username

    return render_template('profile.html', user=user, upload_count=upload_count, total_views=total_views, username=username)

@profile_bp.route('/user_posts/<username>')
def user_posts(username):
    """Display posts of a specific user."""
    # Fetch the user based on the username parameter
    user = User.query.filter_by(username=username).first()
    if not user:
        # Handle case where user does not exist
        flash('User not found', 'error')
        return redirect(url_for('index'))
    
    # Fetch user's posts
    user_posts = Post.query.filter_by(fk_userid=user.id).all()        
    
    # Pre-process image URLs
    for post in user_posts:
        post.img_url = url_for('post.serve_uploaded_image', filename=os.path.basename(post.img_path))
    
    # Calculate total views for the user's posts
    total_views = user.calculate_total_views()

    # Pass the username to the template
    username = user.username
    
    return render_template('user_posts.html', user=user, user_posts=user_posts, total_views=total_views, username=username)

# Route to display posts liked by the user
@profile_bp.route('/user_likes/<username>')
def user_likes(username):
    """Display posts liked by the user."""
    # Ensure the user is logged in
    if not g.user:
        flash('Please log in to view your liked posts.', 'error')
        return redirect(url_for('auth.login'))

    # Fetch the user based on the username parameter
    user = User.query.filter_by(username=username).first_or_404()
    if not user:
        flash('User not found', 'error')
        return redirect(url_for('index'))

    # Fetch the liked posts of the authenticated user
    liked_posts = (
        Post.query
        .join(Like, Post.id == Like.post_id)
        .filter(Like.user_id == user.id)
        .filter(Like.is_like == True)
        .all()
    )

    # Pre-process image URLs for liked posts
    for post in liked_posts:
        post.img_url = url_for('post.serve_uploaded_image', filename=os.path.basename(post.img_path))

    # Calculate total views for the user's posts
    total_views = user.calculate_total_views()

    # Pass the username to the template
    username = user.username

    return render_template('user_likes.html', user=user, liked_posts=liked_posts, total_views=total_views, username=username)

# Route to display comments of the currently logged-in user
@profile_bp.route('/user_comments/<username>')
def user_comments(username):
    """Display comments made by the user."""

    user = User.query.filter_by(username=username).first()

    if not user:
        return redirect(url_for('login'))

    # Fetch user's comments along with associated post information
    user_comments = (
        Comment.query
        .join(Post, Comment.fk_postid == Post.id)  # Join Comment with Post
        .filter(Comment.fk_userid == user.id)  # Filter comments by user ID
        .order_by(Comment.created.desc())
        .all()
    )

    # Pre-process image URLs for each comment's associated post
    for comment in user_comments:
        comment.post.img_url = url_for('post.serve_uploaded_image', filename=os.path.basename(comment.post.img_path))

    # Calculate total views for the user's posts
    total_views = user.calculate_total_views()
    
    # Pass the username to the template
    username = user.username

    return render_template('user_comments.html', user=user, user_comments=user_comments, total_views=total_views, username=username)

# Route to display the about page of the user
@profile_bp.route('/user_about/<username>')
def user_about(username):
    """Display the about page of a specific user."""
    # Retrieve user information based on username (e.g., from the database)
    user = User.query.filter_by(username=username).first()
    if user:

        # Calculate total views for the user's posts
        total_views = user.calculate_total_views()

        # Pass the username to the template
        username = user.username

        return render_template('user_about.html', user=user, total_views=total_views, username=username)
    else:
        # Handle case where user is not found
        return render_template('user_not_found.html')
    
############################################################################################################
# Edit profile

@profile_bp.route('/edit_profile', methods=['GET', 'POST'])
def edit_profile():
    """Edit user profile."""
    form = EditProfileForm(request.form)

    if form.validate_on_submit():
        user = g.user
        
        if user:
            # Update user's information based on form data
            new_username = form.username.data
            new_email = form.email.data
            new_password = form.password.data
            new_about = form.about.data

            # Update username if provided
            if new_username:
                user.username = new_username

            # Update email if provided
            if new_email:
                user.email = new_email

            # Update password if provided
            if new_password:
                hashed_pwd = bcrypt.generate_password_hash(new_password).decode('UTF-8')
                user.password = hashed_pwd

            # Update about if provided
            if new_about:
                user.about = new_about

            # Commit changes to the database
            db.session.commit()

            flash('Profile updated successfully.', 'success')
            return redirect(url_for('profile.profile'))
        else:
            flash('User not found', 'error')
            return redirect(url_for('auth.login'))
    else:
        flash_errors(form)
        return render_template('edit_profile.html', form=form)

def flash_errors(form):
    """Flash form errors."""
    for field, errors in form.errors.items():
        # Skip flashing CSRF token errors
        if field != 'csrf_token':
            for error in errors:
                flash(f"Error in {getattr(form, field).label.text}: {error}", "error")

############################################################################################################
# Delete a user 

@profile_bp.route('/user/delete', methods=['POST'])
def delete_user():
    """Delete a user."""
    if g.user:
        user_id = g.user.id

        # Delete comments by the user
        Comment.query.filter_by(fk_userid=user_id).delete()

        # Delete likes by the user
        Like.query.filter_by(user_id=user_id).delete()

        # Delete user posts
        Post.query.filter_by(fk_userid=user_id).delete()

        # Delete the user from the database
        db.session.delete(g.user)
        db.session.commit()
        
        # Logout the user after deletion
        do_logout()
        
        flash('Your account has been successfully deleted.', 'success')
        return redirect(url_for('index'))  # Redirect to the homepage or another appropriate page
    else:
        flash('You need to be logged in to delete your account.', 'error')
        return redirect(url_for('auth.login'))  # Redirect to the login page if user is not logged in

routes/search.py
from flask import Blueprint, render_template, request, url_for
from models import Post
from routes.helpers import add_user_to_g, do_login, do_logout, CURR_USER_KEY
import os

search_bp = Blueprint('search', __name__, url_prefix='/search')

############################################################################################################
# Search

@search_bp.route('/search')
def search():
    """Handle search queries."""
    # Get the search query from the request
    query = request.args.get('query')

    # Query your database based on the search query using the find_many method
    search_results = Post.find_many(query)

    # Pre-process image URLs
    for post in search_results:
        post.img_url = url_for('serve_uploaded_image', filename=os.path.basename(post.img_path))

    # Render the search results in the search.html template
    return render_template('search.html', query=query, posts=search_results)

templates/author_profile.html
{% extends 'base.html' %}

{% block title %}Author Profile - {{ author.username }}{% endblock %}

{% block content %}

    <div class="card text-center header-card">
        <div class="container mt-4">
            <div class="row">
                <div class="col-md-3">
                    <h3>{{ author.username }}</h3>
                </div>
            </div>
        
        <!-- Navigation Links -->
        <div class="row">
            <div class="col-md-12 text-center">
                <h3>
                    <a href="{{ url_for('author_profile.author_posts', username=author.username) }}">Posts</a>
                    <span class="mx-3"></span>
                    <a href="{{ url_for('author_profile.author_likes', username=author.username) }}">Likes</a>
                    <span class="mx-3"></span>
                    <a href="{{ url_for('author_profile.author_comments', username=author.username) }}">Comments</a>
                    <span class="mx-3"></span>
                    <a href="{{ url_for('author_profile.author_about', username=author.username) }}">About</a>
                </h3>
            </div>
        </div>
        
        <!-- Content Specific to Author Profile -->
        <div class="row">
            <!-- Content Here -->
            <div class="col-md-12">
                <!-- You can display additional information about the author here -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit Post{% endblock %}

{% block content %}
<div class="small-container">
    <div class="card bg-dark text-white">
        <div class="container mt-4">
            <h2>Edit Post</h2>
            <form method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {{ form.title(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.description.label(class="form-control-label") }}
                    {{ form.description(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.upload_image.label(class="form-control-label") }}
                    {{ form.upload_image(class="form-control-file") }}
                </div>
                <button type="submit" class="btn btn-primary">Save Changes</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/user_about.html
{% extends 'base.html' %}
{% block title %}{{ user.username }}'s Posts{% endblock %}

{% block content %}
    <div id="profile-container" class="container mt-4">
        <!-- User Information -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card bg-primary text-white">
                    <div class="header-card">

                        <div class="d-flex w-100 justify-content-between">
                            <h4 id="profile-username" class="card-title">{{ user.username }}</h4>
                            <p>
                                Registered
                                <strong><span id="profile-register-date" class="text-white">{{ user.register_date }}</span></strong>
                            </p>
                        </div>

                        <ul class="list-inline float-right">
                            <li class="list-inline-item">
                                <i class="fas fa-upload"></i>
                                <strong><span id="post-uploads">{{ user.uploads }}</span></strong> uploads
                            </li>
                            <li class="list-inline-item">
                                <i class="fas fa-eye"></i>
                                <strong><span id="post-views">{{ total_views }}</span></strong> views
                            </li>
                        </ul>

                        <div class="col-md-12 text-center text-white">
                            <h3>
                                <a href="{{ url_for('profile.user_posts', username=username) }}">Posts</a>
                                <span class="mx-3"></span>
                                <a href="{{ url_for('profile.user_likes', username=username) }}">Likes</a>
                                <span class="mx-3"></span>
                                <a href="{{ url_for('profile.user_comments', username=username) }}">Comments</a>
                                <span class="mx-3"></span>
                                <a href="{{ url_for('profile.user_about', username=username) }}">About</a>
                            </h3>
                        </div>

                        <!-- Edit and Delete User Button -->
                        <div class="float-right d-flex justify-content-between align-items-center">
                            <div class="dropdown">
                                <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="profileDropdownButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa-solid fa-ellipsis"></i>
                                </button>
                                <div class="dropdown-menu bg-dark" aria-labelledby="profileDropdownButton">
                                    <a class="dropdown-item text-white" href="{{ url_for('profile.edit_profile') }}">Edit Profile</a>
                                    <form id="delete-user-form" action="{{ url_for('profile.delete_user') }}" method="POST">
                                        <button type="submit" class="dropdown-item text-white delete-button">Delete Profile</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>

        <!-- User's About -->
        <div class="container mt-4">
            <div class="card bg-light">
                <div class="card-body">
                    <h2>About</h2>
                    <p>{{ user.about }}</p> <!-- Display user's about information -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user_comments.html
{% extends 'base.html' %}
{% block title %}{{ user.username }}'s Posts{% endblock %}

{% block content %}
    <div id="profile-container" class="container mt-4">
        <!-- User Information -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card bg-primary text-white">
                    <div class="header-card">

                        <div class="d-flex w-100 justify-content-between">
                            <h4 id="profile-username" class="card-title">{{ user.username }}</h4>
                            <p>
                                Registered
                                <strong><span id="profile-register-date" class="text-white">{{ user.register_date }}</span></strong>
                            </p>
                        </div>

                        <ul class="list-inline float-right">
                            <li class="list-inline-item">
                                <i class="fas fa-upload"></i>
                                <strong><span id="post-uploads">{{ user.uploads }}</span></strong> uploads
                            </li>
                            <li class="list-inline-item">
                                <i class="fas fa-eye"></i>
                                <strong><span id="post-views">{{ total_views }}</span></strong> views
                            </li>
                        </ul>

                        <div class="col-md-12 text-center text-white">
                            <h3>
                                <a href="{{ url_for('profile.user_posts', username=username) }}">Posts</a>
                                <span class="mx-3"></span>
                                <a href="{{ url_for('profile.user_likes', username=username) }}">Likes</a>
                                <span class="mx-3"></span>
                                <a href="{{ url_for('profile.user_comments', username=username) }}">Comments</a>
                                <span class="mx-3"></span>
                                <a href="{{ url_for('profile.user_about', username=username) }}">About</a>
                            </h3>
                        </div>

                        <!-- Edit and Delete User Button -->
                        <div class="float-right d-flex justify-content-between align-items-center">
                            <div class="dropdown">
                                <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="profileDropdownButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa-solid fa-ellipsis"></i>
                                </button>
                                <div class="dropdown-menu bg-dark" aria-labelledby="profileDropdownButton">
                                    <a class="dropdown-item text-white" href="{{ url_for('profile.edit_profile') }}">Edit Profile</a>
                                    <form id="delete-user-form" action="{{ url_for('profile.delete_user') }}" method="POST">
                                        <button type="submit" class="dropdown-item text-white delete-button">Delete Profile</button>
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <!-- User Comments -->
        <div class="row mt-4">
            {% if user_comments %}
                <!-- Iterate through user comments if they exist -->
                {% for comment in user_comments %}
                    <div class="col-sm-12 mb-4">
                        <div class="card bg-dark text-white">
                            <div class="card-body">
                                <div class="row">
                                    <!-- Image Container -->
                                    <div class="col-1">
                                        <a href="{{ url_for('post.show_image', post_id=comment.post.id) }}">
                                            <img src="{{ comment.post.img_url }}" class="img-fluid rounded-square" alt="Post Image">
                                        </a>
                                    </div>
                                    <!-- Comment Content -->
                                    <div class="col-9">
                                        <div class="comment-header">
                                            <a href="{{ url_for('author_profile.author_profile', username=comment.user.username) }}" class="username">{{ comment.user.username }}</a>
                                            <small class="text-muted">{{ comment.created }}</small>
                                            <!-- Add dropdown menu for delete option -->
                                            {% if g.user and g.user.id == comment.user.id %}
                                                <div class="dropdown float-right">
                                                    <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton_{{ comment.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fa-solid fa-ellipsis"></i>
                                                    </button>
                                                    <div class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuButton_{{ comment.id }}">
                                                        <form action="{{ url_for('comment.delete_comment', comment_id=comment.id) }}" method="post">
                                                            <button type="submit" class="dropdown-item text-white">Delete Comment</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="comment-text">
                                            {{ comment.text }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <!-- Display message if user hasn't made any comments -->
                <div class="col-sm-12 mb-4">
                    <p>No comments yet.</p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <!-- Axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <!-- Moment.js -->
    <script src="https://momentjs.com/downloads/moment.js"></script>
{% endblock %}